nmap *   <Plug>(asterisk-*)
nmap #   <Plug>(asterisk-#)
nmap g*  <Plug>(asterisk-g*)
nmap g#  <Plug>(asterisk-g#)
nmap z*  <Plug>(asterisk-z*)
nmap z#  <Plug>(asterisk-z#)
nmap gz* <Plug>(asterisk-gz*)
nmap gz# <Plug>(asterisk-gz#)
