# PACKAGES:=custom X vim
PACKAGES:=$(shell ls -d *"/" | cut -d/ -f1 | tr '\n' ' ')

STOW:=$(shell which stow)
STOW_FLAGS:=--restow --target=$(HOME)

PACKAGE_MANAGER:=$(shell which yay)
PACKAGE_MANAGER_FLAGS_INSTALL:=-S --needed
PACKAGE_MANAGER_FLAGS_LIST_INSTALLED_PACKAGES:=-Qq

PACGRAPH:=$(shell which pacgraph)
PACGRAPH_BACKGROUND:=                     \#000000
PACGRAPH_LINK:=                           \#cdcdcd
PACGRAPH_TOP:=                            \#00ffff
PACGRAPH_DEP:=                            \#ff00ff
PACGRAPH_HIGHLIGHT_SELECTED_PACKAGE:=     \#ffff00
PACGRAPH_HIGHLIGHT_SELECTED_DEPENDENCIES:=\#ffff00
PACGRAPH_HIGHLIGHT_SELECTED_NEEDED_BY:=   \#ffff00
PACGRAPH_FLAGS:=--point 24 256 --no-compression --show-req-by --disable-palette --background=\$(PACGRAPH_BACKGROUND) --link=\$(PACGRAPH_LINK) --top=\$(PACGRAPH_TOP) --dep=\$(PACGRAPH_DEP) --highlight=\$(PACGRAPH_HIGHLIGHT_SELECTED_PACKAGE) \$(PACGRAPH_HIGHLIGHT_SELECTED_DEPENDENCIES) \$(PACGRAPH_HIGHLIGHT_SELECTED_NEEDED_BY)
