#!/bin/sh

killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for MONITOR in $(bspc query --monitors --names); do
	polybar -r ${MONITOR} &
done
