#!/bin/sh

killall -q polybar
sleep 1 # fix strange bug
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for monitor in $(bspc query --monitors --names); do
	polybar -r ${monitor} &
done
