#!/usr/bin/env sh

# This script move the selected window to the bottom left of the screen.
WID=$(xdotool getwindowfocus)

# The window will take up no more than a third of
# the width or height of the screen.
H=$(( $(xdotool getdisplaygeometry | awk '{print $1}') / 6 ))
W=$(( $(xdotool getdisplaygeometry | awk '{print $2}') / 6 ))

xdotool windowsize "$WID" $H $W

H=$(xdotool getwindowgeometry "$WID" | grep Geometry | sed -e 's/x/ /g' | awk '{print $2}')
H=$(xdotool getwindowgeometry "$WID" | grep Geometry | sed -e 's/x/ /g' | awk '{print $3}')

X=$(( $(xdotool getdisplaygeometry | awk '{print $1}') - W ))
Y=$(( $(xdotool getdisplaygeometry | awk '{print $2}') - H ))
xdotool windowmove "$WID" $X $Y
