#!/usr/bin/env sh

TERMINAL=st
COMMAND=$1
NAME=${2:-$(basename $COMMAND)}

case "$NAME" in zsh|ranger|lf)
	WINDOW_PID="$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)"
	CLIENT_PID="$(echo "$(pstree -lpA "$WINDOW_PID" | tail -n 1)" | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')"
	SESSION_NAME="$(tmux list-clients -F "#{session_name} #{client_pid}" | grep "$CLIENT_PID" | cut -d' ' -f 1)"
	PANE_PID="$(tmux list-panes -a -F "#{pane_pid} #{session_name} #{pane_active}" | grep "$SESSION_NAME 1" | cut -d' ' -f 1)"
	CD="$(readlink /proc/"$PANE_PID"/cwd)"
	if [ "$CD" = "$HOME" ]; then
		CD=
	fi
esac

WINDOWID="$(xdotool search --class "^preloaded_$NAME$" | head -n 1)"
if [ -n "$WINDOWID" ]; then # WE HAVE X WINDOW
	if ! tmux list-sessions -F "#{session_name}" | grep preloaded_$NAME >/dev/null; then # WE DON'T HAVE TMUX SESSION
		case $NAME in
			zsh|ranger|lf)
				if [ -n "${CD}" ]; then
					case $NAME in
						zsh)
							tmux new-session -d -s "preloaded_$NAME" $NAME
							tmux send-keys -t "preloaded_$NAME" "cd $CD" "Enter" "C-l"
							;;
						ranger|lf)
							tmux new-session -d -s "preloaded_$NAME" $COMMAND $CD
							;;
					esac
				else
					tmux new-session -d -s "preloaded_$NAME" $COMMAND
				fi
				;;
			*)
				tmux new-session -d -s "preloaded_$NAME" $COMMAND
				;;
		esac
		case $NAME in
			todoman)
				tmux send-keys -t "preloaded_$NAME" "list" "Enter"
				;;
		esac
	fi
	if [ -n "${CD}" ]; then
		case $NAME in
			zsh)
				tmux send-keys -t "preloaded_$NAME" "cd $CD" "Enter"
				;;
			ranger|lf)
				tmux send-keys -t "preloaded_$NAME" ":"
				tmux send-keys -t "preloaded_$NAME" "cd $CD" "Enter"
				;;
		esac
	fi
	case $NAME in
		todoman)
			tmux send-keys -t "preloaded_$NAME" "list" "Enter"
			;;
	esac
	RANDOMID="$(random-string '0-9' 6)"
	WINDOWID="$(xdotool search --class "^preloaded_$NAME$" | tail -n 1)"
	bspc node "$WINDOWID" --state tiled
	bspc node "$WINDOWID" --to-node 'any.leaf.!window.local' --follow ||
		bspc node "$WINDOWID" --to-node "$(bspc query -N -n)" --follow ||
		bspc node "$WINDOWID" --to-desktop "$(bspc query -D -d)" --follow
	bspc node "$WINDOWID" --focus
	xdotool set_window --class "$NAME" "$WINDOWID"
	[ "$NAME" = "zsh" ] && tmux send-keys -t "preloaded_$NAME" "C-l"
	tmux rename-session -t "preloaded_$NAME" "$RANDOMID"
else
	case $NAME in
		zsh|ranger|lf)
			if [ -n "${CD}" ]; then
				case $NAME in
					zsh)
						tmux new-session -d -s "preloaded_$NAME" $NAME
						tmux send-keys -t "preloaded_$NAME" "cd $CD" "Enter" "C-l"
						;;
					ranger|lf)
						tmux new-session -d -s "preloaded_$NAME" $COMMAND $CD
						;;
				esac
			else
				tmux new-session -d -s "preloaded_$NAME" $COMMAND
			fi
			;;
		*)
			tmux new-session -d -s "preloaded_$NAME" $COMMAND
			;;
	esac
	case $NAME in
		todoman)
			tmux send-keys -t "preloaded_$NAME" "list" "Enter"
			;;
	esac
	$TERMINAL -c "preloaded_$NAME" -e "tmux" "attach-session" "-t" "preloaded_$NAME" &
	RANDOMID="$(random-string '0-9' 6)"
	until [ "$(xdotool search --class "^preloaded_$NAME$")" ]; do :; done
	WINDOWID="$(xdotool search --class "^preloaded_$NAME$" | tail -n 1)"
	bspc node "$WINDOWID" --state tiled
	bspc node "$WINDOWID" --to-node 'any.leaf.!window.local' --follow ||
		bspc node "$WINDOWID" --to-node "$(bspc query -N -n)" --follow ||
		bspc node "$WINDOWID" --to-desktop "$(bspc query -D -d)" --follow
	bspc node "$WINDOWID" --focus
	xdotool set_window --class "$NAME" "$WINDOWID"
	tmux rename-session -t "preloaded_$NAME" "$RANDOMID"
fi
if [ -z "$(xdotool search --classname "^preloaded_$NAME$")" ]; then
	tmux new-session -d -s "preloaded_$NAME" $COMMAND
	$TERMINAL -c "preloaded_$NAME" -e "tmux" "attach-session" "-t" "preloaded_$NAME" &
fi
