#!/usr/bin/env sh

# calendar, todo list, address book
notify-send '🔄 SYNCHRONIZING CALENDAR'
notify-send '🔄 SYNCHRONIZING TODO LIST'
notify-send '🔄 SYNCHRONIZING ADDRESS BOOK'
vdirsyncer discover
vdirsyncer sync
vdirsyncer metasync
TEMPFILE=$(tempname $(basename $0))
cat /dev/null $(find $XDG_DATA_HOME/contacts/personal/ -type f -name '*.vcf') >> $TEMPFILE
cat /dev/null $(find $XDG_DATA_HOME/contacts/school/   -type f -name '*.vcf') >> $TEMPFILE
mv $HOME/.abook/addressbook $HOME/.abook/addressbook~
abook --convert --infile "$TEMPFILE" --informat vcard --outfile $HOME/.abook/addressbook --outformat abook
rm $TEMPFILE

# mail
notify-send '🔄 SYNCHRONIZING MAIL'

notify-send '✔ FINISHED SYNCHRONIZING'
