nmap s  <plug>(SubversiveSubstitute)
nmap ss <plug>(SubversiveSubstituteLine)
nmap S  <plug>(SubversiveSubstituteToEndOfLine)

" nmap <leader>s  <plug>(SubversiveSubstituteRange)
" xmap <leader>s  <plug>(SubversiveSubstituteRange)
" nmap <leader>ss <plug>(SubversiveSubstituteWordRange)
" nmap <leader>s <plug>(SubversiveSubvertRange)
" xmap <leader>s <plug>(SubversiveSubvertRange)
" nmap <leader>ss <plug>(SubversiveSubvertWordRange)
