let g:multi_cursor_use_default_mapping   = 0
let g:multi_cursor_exit_from_visual_mode = 0
" let g:multi_cursor_start_word_key      = ''
" let g:multi_cursor_select_all_word_key = ''
let g:multi_cursor_start_key          ='<C-n>'
let g:multi_cursor_select_all_key     ='<C-S-A>'
let g:multi_cursor_next_key           ='<C-n>'
let g:multi_cursor_prev_key           ='<C-p>'
let g:multi_cursor_skip_key           ='<C-s>'
let g:multi_cursor_quit_key           ='<ESC>'
