#!/bin/sh
alias ka="killall"
alias history="history 1"
alias l="ls -Al"
alias ll="ls -Al"
alias gdb="gdb -q"
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"
alias calcurse="calcurse -D ~/.config/calcurse"
alias magit="nvim -c Magit"
alias p="sudo pacman"
alias SS="sudo systemctl"
alias f="$FILE"
alias g="git"
alias qgr="git commit -am "common""
alias trem="transmission-remote"
alias e="$EDITOR"
alias v="$EDITOR"
alias x="sxiv -ft *"
alias sdn="sudo shutdown -h now"
alias gua="git remote | xargs -L1 git push --all"
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'"
alias yta="yt -x -f bestaudio/best"
alias YT="youtube-viewer"
alias ref="shortcuts >/dev/null; source ~/.config/shortcutrc"
alias upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks"
alias lsp="pacman -Qett --color=always | less"
alias ffmpeg="ffmpeg -hide_banner"
alias tree="tree -C"

eval "$(thefuck --alias)"

# command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
sv() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}
