#!/usr/bin/env sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

xsetroot -cursor_name left_ptr

if bspc query --monitors --names | grep VGA1 >/dev/null; then
	xrandr --output VGA1  --auto --scale 1.0x1.0 --rotate normal --primary \
	       --output LVDS1 --auto --scale 1.0x1.0 --rotate normal --below VGA1
	bspc monitor VGA1  -d 1 2 3 4 5 6 7 8 9
	bspc monitor LVDS1 -d 0 H
else
	xrandr --output LVDS1 --auto --scale 1.0x1.0 --rotate normal --primary
	bspc monitor -d H 1 2 3 4 5 6 7 8 9 0 H
fi

bspc desktop H --layout monocle

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# SETTINGS {{{
# 		Colors are in the form #RRGGBB, booleans are true, on, false or off.
# 		All the boolean settings are false by default unless stated otherwise.
# 	Global Settings
  		normal_border_color='#00FFFF'
# 			Color of the border of an unfocused window.
		active_border_color='#00FFFF'
# 			Color of the border of a focused window of an unfocused monitor.
		focused_border_color='#FF00FF'
# 			Color of the border of a focused window of a focused monitor.
		presel_feedback_color='#FF0000'
# 			Color of the node --presel-{dir,ratio} message feedback area.
		split_ratio=0.52
# 			Default split ratio.
		status_prefix=
# 			Prefix prepended to each of the status lines.
		external_rules_command="$XDG_CONFIG_HOME/bspwm/rules"
# 			Absolute path to the command used to retrieve rule consequences. The command will receive the following arguments: window ID, class name, instance name,
# 			and intermediate consequences. The output of that command must have the following format: key1=value1 key2=value2 ...  (the valid key/value pairs are
# 			given in the description of the rule command).
		automatic_scheme=longest_side
# 			The insertion scheme used when the insertion point is in automatic mode. Accept the following values: longest_side, alternate, spiral.
		initial_polarity=
# 			On which child should a new window be attached when adding a window on a single window tree in automatic mode. Accept the following values: first_child,
# 			second_child.
		directional_focus_tightness=
# 			The tightness of the algorithm used to decide whether a window is on the DIR side of another window. Accept the following values: high, low.
		removal_adjustment=
# 			Adjust the brother when unlinking a node from the tree in accordance with the automatic insertion scheme.
		presel_feedback=true
# 			Draw the preselection feedback area. Defaults to true.
		borderless_monocle=true
# 			Remove borders of tiled windows for the monocle desktop layout.
		gapless_monocle=true
# 			Remove gaps of tiled windows for the monocle desktop layout.
		top_monocle_padding=
		right_monocle_padding=
		bottom_monocle_padding=
		left_monocle_padding=
# 			Padding space added at the sides of the screen for the monocle desktop layout.
		single_monocle=true
# 			Set the desktop layout to monocle if there’s only one tiled window in the tree.
		pointer_motion_interval=
# 			The minimum interval, in milliseconds, between two motion notify events.
		pointer_modifier=mod4
# 			Keyboard modifier used for moving or resizing windows. Accept the following values: shift, control, lock, mod1, mod2, mod3, mod4, mod5.
		pointer_action1=move
		pointer_action2=none
		pointer_action3=resize_corner
# 			Action performed when pressing pointer_modifier + button<n>. Accept the following values: move, resize_side, resize_corner, focus, none.
		click_to_focus=false
# 			Button used for focusing a window (or a monitor). The possible values are: button1, button2, button3, any, none. Defaults to button1.
		swallow_first_click=false
# 			Don’t replay the click that makes a window focused if click_to_focus isn’t none.
		focus_follows_pointer=true
# 			Focus the window under the pointer.
		pointer_follows_focus=true
			# When focusing a window, put the pointer at its center.
		pointer_follows_monitor=true
# 			When focusing a monitor, put the pointer at its center.
		mapping_events_count=-1
# 			Handle the next mapping_events_count mapping notify events. A negative value implies that every event needs to be handled.
		ignore_ewmh_focus=true
# 			Ignore EWMH focus requests coming from applications.
		ignore_ewmh_fullscreen=none
# 			Block the fullscreen state transitions that originate from an EWMH request. The possible values are: none, all, or a comma separated list of the following
# 			values: enter, exit.
		ignore_ewmh_struts=false
# 			Ignore strut hinting from clients requesting to reserve space (i.e. task bars).
		center_pseudo_tiled=
# 			Center pseudo tiled windows into their tiling rectangles. Defaults to true.
		honor_size_hints=false # makes resizing with mouse shitty
# 			Apply ICCCM window size hints.
		remove_disabled_monitors=true
# 			Consider disabled monitors as disconnected.
		remove_unplugged_monitors=true
# 			Remove unplugged monitors.
		merge_overlapping_monitors=true
# 			Merge overlapping monitors (the bigger remains).
# 	Monitor and Desktop Settings
		top_padding=16
		right_padding=0
		bottom_padding=0
		left_padding=0
# 			Padding space added at the sides of the monitor or desktop.
# 	Desktop Settings
		window_gap=2
# 			Size of the gap that separates windows.
# 	Node Settings
		border_width=1
# 			Window border width.
	# {{{
		[ -n "$normal_border_color"         ] && bspc config normal_border_color         "$normal_border_color"
		[ -n "$active_border_color"         ] && bspc config active_border_color         "$active_border_color"
		[ -n "$focused_border_color"        ] && bspc config focused_border_color        "$focused_border_color"
		[ -n "$presel_feedback_color"       ] && bspc config presel_feedback_color       "$presel_feedback_color"
		[ -n "$split_ratio"                 ] && bspc config split_ratio                 "$split_ratio"
		[ -n "$status_prefix"               ] && bspc config status_prefix               "$status_prefix"
		[ -n "$external_rules_command"      ] && bspc config external_rules_command      "$external_rules_command"
		[ -n "$automatic_scheme"            ] && bspc config automatic_scheme            "$automatic_scheme"
		[ -n "$initial_polarity"            ] && bspc config initial_polarity            "$initial_polarity"
		[ -n "$directional_focus_tightness" ] && bspc config directional_focus_tightness "$directional_focus_tightness"
		[ -n "$removal_adjustment"          ] && bspc config removal_adjustment          "$removal_adjustment"
		[ -n "$presel_feedback"             ] && bspc config presel_feedback             "$presel_feedback"
		[ -n "$borderless_monocle"          ] && bspc config borderless_monocle          "$borderless_monocle"
		[ -n "$gapless_monocle"             ] && bspc config gapless_monocle             "$gapless_monocle"
		[ -n "$top_monocle_padding"         ] && bspc config top_monocle_padding         "$top_monocle_padding"
		[ -n "$right_monocle_padding"       ] && bspc config right_monocle_padding       "$right_monocle_padding"
		[ -n "$bottom_monocle_padding"      ] && bspc config bottom_monocle_padding      "$bottom_monocle_padding"
		[ -n "$left_monocle_padding"        ] && bspc config left_monocle_padding        "$left_monocle_padding"
		[ -n "$single_monocle"              ] && bspc config single_monocle              "$single_monocle"
		[ -n "$pointer_motion_interval"     ] && bspc config pointer_motion_interval     "$pointer_motion_interval"
		[ -n "$pointer_modifier"            ] && bspc config pointer_modifier            "$pointer_modifier"
		[ -n "$pointer_action1"             ] && bspc config pointer_action1             "$pointer_action1"
		[ -n "$pointer_action2"             ] && bspc config pointer_action2             "$pointer_action2"
		[ -n "$pointer_action3"             ] && bspc config pointer_action3             "$pointer_action3"
		[ -n "$click_to_focus"              ] && bspc config click_to_focus              "$click_to_focus"
		[ -n "$swallow_first_click"         ] && bspc config swallow_first_click         "$swallow_first_click"
		[ -n "$focus_follows_pointer"       ] && bspc config focus_follows_pointer       "$focus_follows_pointer"
		[ -n "$pointer_follows_focus"       ] && bspc config pointer_follows_focus       "$pointer_follows_focus"
		[ -n "$pointer_follows_monitor"     ] && bspc config pointer_follows_monitor     "$pointer_follows_monitor"
		[ -n "$mapping_events_count"        ] && bspc config mapping_events_count        "$mapping_events_count"
		[ -n "$ignore_ewmh_focus"           ] && bspc config ignore_ewmh_focus           "$ignore_ewmh_focus"
		[ -n "$ignore_ewmh_fullscreen"      ] && bspc config ignore_ewmh_fullscreen      "$ignore_ewmh_fullscreen"
		[ -n "$ignore_ewmh_struts"          ] && bspc config ignore_ewmh_struts          "$ignore_ewmh_struts"
		[ -n "$center_pseudo_tiled"         ] && bspc config center_pseudo_tiled         "$center_pseudo_tiled"
		[ -n "$honor_size_hints"            ] && bspc config honor_size_hints            "$honor_size_hints"
		[ -n "$remove_disabled_monitors"    ] && bspc config remove_disabled_monitors    "$remove_disabled_monitors"
		[ -n "$remove_unplugged_monitors"   ] && bspc config remove_unplugged_monitors   "$remove_unplugged_monitors"
		[ -n "$merge_overlapping_monitors"  ] && bspc config merge_overlapping_monitors  "$merge_overlapping_monitors"
		[ -n "$top_padding"                 ] && bspc config top_padding                 "$top_padding"
		[ -n "$right_padding"               ] && bspc config right_padding               "$right_padding"
		[ -n "$bottom_padding"              ] && bspc config bottom_padding              "$bottom_padding"
		[ -n "$left_padding"                ] && bspc config left_padding                "$left_padding"
		[ -n "$window_gap"                  ] && bspc config window_gap                  "$window_gap"
		[ -n "$border_width"                ] && bspc config border_width                "$border_width"
	# }}}
# }}}
# autostart {{{
xrdb $XDG_CONFIG_HOME/Xresources        & # Use Xresources colors/settings on startup
remaps                                  & # run the remaps script, switching caps/esc and more; check it for more info
xset r rate 200 60                      & # Speed xrate up
setbg                                   & # set the background with the `setbg` script
[ ! "$(pgrep sxhkd    )" ] && sxhkd     & # keybinds
[ ! "$(pgrep picom    )" ] && picom     & # X compositor
[ ! "$(pgrep dunst    )" ] && dunst     & # dunst for notifications
[ ! "$(pgrep unclutter)" ] && unclutter & # Remove mouse when idle
launch-polybar                          & # status bar

# border=off => use startup rules
bspc rule --add 'discord'       --one-shot "border=off" && bspc rule --add 'discord' --one-shot "border=off" && discord            &
bspc rule --add 'Pidgin'        --one-shot "border=off" && bspc rule --add 'Pidgin'  --one-shot "border=off" && pidgin             &
bspc rule --add 'Brave-browser' --one-shot "border=off" &&                                                      brave              &
bspc rule --add '*:surf'        --one-shot "border=off" &&                                                      $BROWSER           &
bspc rule --add '*'             --one-shot "border=off" &&                                                      gtk-launch spotify &
# }}}
