#! /bin/sh

xsetroot -cursor_name left_ptr

if bspc query --monitors --names | grep VGA1 >/dev/null; then
	xrandr --output VGA1  --auto --scale 1.0x1.0 --rotate normal --primary \
	       --output LVDS1 --auto --scale 1.0x1.0 --rotate normal --below VGA1
	bspc monitor VGA1  -d 1 2 3 4 5 6 7 8 9
	bspc monitor LVDS1 -d 0
else
	xrandr --output LVDS1 --auto --scale 1.0x1.0 --rotate normal --primary
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width             1
bspc config window_gap               2
bspc config top_padding             16
bspc config split_ratio              0.52
bspc config focus_follows_pointer true
bspc config automatic_scheme      longest_side

bspc config borderless_monocle    true
bspc config    gapless_monocle    true

bspc config presel_feedback_color '#ff0000'
bspc config presel_feedback       true

bspc config  normal_border_color  '#00ffff'
bspc config  active_border_color  '#00ffff'
bspc config focused_border_color  '#ff00ff'

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"
bspc rule -a Brave desktop='^5' follow=on
bspc rule -a Zathura state=tiled

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

bspc config external_rules_command "${XDG_CONFIG_HOME}/bspwm/floaters"

xrdb ${XDG_CONFIG_HOME}/Xresources      & # Use Xresources colors/settings on startup
remaps                                  & # run the remaps script, switching caps/esc and more; check it for more info
xset r rate 200 60                      & # Speed xrate up
setbg                                   & # set the background with the `setbg` script
[ ! "$(pgrep sxhkd    )" ] && sxhkd     & # keybinds
[ ! "$(pgrep picom    )" ] && picom     & # X compositor
[ ! "$(pgrep dunst    )" ] && dunst     & # dunst for notifications
[ ! "$(pgrep unclutter)" ] && unclutter & # Remove mouse when idle
launch-polybar                          & # status bar
