let g:multi_cursor_use_default_mapping   = 0
let g:multi_cursor_exit_from_visual_mode = 0
" let g:multi_cursor_start_word_key      = ''
" let g:multi_cursor_select_all_word_key = ''
let g:multi_cursor_start_key          ='<C-N>'
let g:multi_cursor_select_all_key     ='<leader>r'
let g:multi_cursor_next_key           ='<C-N>'
let g:multi_cursor_prev_key           ='<C-P>'
let g:multi_cursor_skip_key           ='<C-S>'
let g:multi_cursor_quit_key           ='<Esc>'
