#+TITLE: Systems Configuration
#+AUTHOR: Comrade Martin Miroslavovich Michalec
#+EMAIL: Martin@Michalec.dev

#+STARTUP: overview
#+PROPERTY: header-args            :tangle-mode (identity #o444) :mkdirp yes
#+PROPERTY: header-args:conf-space :tangle-mode (identity #o444) :mkdirp yes
#+PROPERTY: header-args:shell      :tangle-mode (identity #o555) :mkdirp yes :shebang "#!/bin/sh"
#+PROPERTY: header-args:makefile   :tangle-mode (identity #o444) :mkdirp yes :tangle ../../script/20-Systems.makefile

* Channels

Guix has a concept of [[https://guix.gnu.org/manual/en/html_node/Channels.html#Channels][channels]], git repositories containing Guix
package definitions. Aside from the =%default-channels= list, I also use
the [[https://gitlab.com/nonguix/nonguix][Nonguix]] channel to install packages that aren't included with Guix
by default like the non-free Linux kernel in order to use my WIFI card.

~~/.config/guix/channels.scm~:

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/channels.scm

  (cons* (channel
          (name 'nonguix)
          (url "https://gitlab.com/nonguix/nonguix")
          (introduction
           (make-channel-introduction
            "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
            (openpgp-fingerprint
             "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5"))))
         (channel
          (name 'flat)
          (url "https://github.com/flatwhatson/guix-channel")
          (commit "a14d79fc33649f55755fb4e705ab82de7852d8da"))
         %default-channels)

#+END_SRC

* Systems
** Base Configuration
Base configuration of machines managed with Guix (Desktops/Laptops).

Configurations deriving from ~base-operating-system~ must execute ~guix
system~ like so:

#+BEGIN_SRC shell

  sudo -E guix system -L ~/dotfiles/.config/guix/systems reconfigure ~/dotfiles/.config/guix/systems/${SYSTEM_NAME}.scm

#+END_SRC

~~/.config/guix/systems/base-system.scm~:

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/systems/base-system.scm

  (define-module (base-system)
    #:use-module (gnu)
    #:use-module (srfi srfi-1)
    #:use-module (gnu system nss)
    #:use-module (gnu services pm)
    #:use-module (gnu services cups)
    #:use-module (gnu services desktop)
    #:use-module (gnu services docker)
    #:use-module (gnu services networking)
    #:use-module (gnu services virtualization)
    #:use-module (gnu packages wm)
    #:use-module (gnu packages cups)
    #:use-module (gnu packages vim)
    #:use-module (gnu packages gtk)
    #:use-module (gnu packages xorg)
    #:use-module (gnu packages emacs)
    #:use-module (gnu packages file-systems)
    #:use-module (gnu packages mtools)
    #:use-module (gnu packages linux)
    #:use-module (gnu packages audio)
    #:use-module (gnu packages pulseaudio)
    #:use-module (gnu packages web-browsers)
    #:use-module (gnu packages version-control)
    #:use-module (gnu packages package-management)
    #:use-module (nongnu packages linux)
    #:use-module (nongnu system linux-initrd))

  (use-service-modules nix)
  (use-service-modules desktop xorg)
  (use-package-modules certs)
  (use-package-modules shells)

#+END_SRC

~udev-rule~ allowing members of the ~video~ group control of screen brightness.

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/systems/base-system.scm

  (define %backlight-udev-rule
    (udev-rule
     "90-backlight.rules"
     (string-append "ACTION==\"add\", SUBSYSTEM==\"backlight\", "
                    "RUN+=\"/run/current-system/profile/bin/chgrp video /sys/class/backlight/%k/brightness\""
                    "\n"
                    "ACTION==\"add\", SUBSYSTEM==\"backlight\", "
                    "RUN+=\"/run/current-system/profile/bin/chmod g+w /sys/class/backlight/%k/brightness\"")))

#+END_SRC

~udev-rule~ changing the acceleration and speed of TrackPoint.

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/systems/base-system.scm

  (define %trackpoint-udev-rule
    (udev-rule
     "10-trackpoint.rules"
     (string-append "ACTION==\"add\", "
                    "SUBSYSTEM==\"input\", "
                    "ATTR{name}==\"*TrackPoint*\", "
                    "ATTR{device/sensitivity}=\"240\", "
                    "ATTR{device/speed}=\"200\"")))

#+END_SRC

Use the ~libinput~ driver for all devices since it's a bit more modern
that the default.

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/systems/base-system.scm

  (define %xorg-libinput-config "
    Section \"InputClass\"
      Identifier \"Touchpads\"
      Driver \"libinput\"
      MatchDevicePath \"/dev/input/event*\"
      MatchIsTouchpad \"on\"

      Option \"Tapping\" \"on\"
      Option \"TappingDrag\" \"on\"
      Option \"DisableWhileTyping\" \"on\"
      Option \"MiddleEmulation\" \"on\"
      Option \"ScrollMethod\" \"twofinger\"
    EndSection
    Section \"InputClass\"
      Identifier \"Keyboards\"
      Driver \"libinput\"
      MatchDevicePath \"/dev/input/event*\"
      MatchIsKeyboard \"on\"
    EndSection
    ")

#+END_SRC

Define the ~base-operating-system~ which will be inherited by all
machine configurations.

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/systems/base-system.scm

  (define-public base-operating-system
    (operating-system
     (host-name "EmacsOS")
     (timezone "Europe/Bratislava")
     (locale "en_US.utf8")
     (keyboard-layout
      (keyboard-layout "us" "altgr-intl" #:model "thinkpad"))

     ;; Use non-free Linux kernel and firmware.
     (kernel linux)
     (firmware (list linux-firmware))
     (initrd microcode-initrd)

     ;; Use the UEFI variant of GRUB
     ;; with the EFI System Partition mounted on /boot/efi.
     (bootloader (bootloader-configuration
                  (bootloader grub-efi-bootloader)
                  (targets '("/boot/efi"))
                  (timeout 3)
                  (theme (grub-theme
                          (inherit (grub-theme))
                          ;; (color-normal    ((fg . light-gray  ) (bg . black)))
                          ;; (color-highlight ((fg .       yellow) (bg . black)))
                          (image #f)
                          (gfxmode '("1366x768x32" "auto"))))

                  (keyboard-layout keyboard-layout)))

     ;; Guix enforces a filesystem entry...
     ;; This is meant to be overridden.
     (file-systems (cons*
                    (file-system
                     (mount-point "/tmp")
                     (device "none")
                     (type "tmpfs")
                     (check? #f))
                    %base-file-systems))

     (users (cons*
             (user-account
              (name "comrade-martin")
              (comment "Comrade Martin Miroslavovich Michalec")
              (group "users")
              (home-directory "/home/comrade-martin")
              (supplementary-groups
               '("wheel"    ;; Use sudo without password.
                 "tty"      ;;
                 "input"    ;;
                 "docker"   ;; Control docker service.
                 "realtime" ;; Allow realtime scheduling.
                 "lp"       ;; Control bluetooth devices.
                 "netdev"   ;; Control network devices.
                 "audio"    ;; Control audio devices.
                 "video"))) ;; Control video devices.
             %base-user-accounts))

     (groups (cons*
              (user-group
               (system? #t)
               (name "realtime"))
              %base-groups))

     (packages
      (append
       (list
        (specification->package "nss-certs") ;; HTTPS access
        (specification->package "gvfs")      ;; User mounts
        (specification->package "ntfs-3g")
        (specification->package "exfat-utils")
        (specification->package "fuse-exfat")
        (specification->package "stow")
        (specification->package "vim")
        (specification->package "xterm")
        (specification->package "bluez")
        (specification->package "bluez-alsa")
        (specification->package "pulseaudio")
        (specification->package "tlp")
        (specification->package "xf86-input-libinput")
        (specification->package "git")
        (specification->package "emacs")
        (specification->package "emacs-exwm")
        (specification->package "emacs-desktop-environment"))
       %base-packages))

   (services
    (cons*
     (service tlp-service-type
              (tlp-configuration
               (cpu-boost-on-ac? #t)
               (wifi-pwr-on-bat? #t)))
     ;; Enables JACK to enter realtime mode
     (pam-limits-service
      (list
       (pam-limits-entry "@realtime"
                         'both
                         'rtprio 99)
       (pam-limits-entry "@realtime"
                         'both
                         'memlock
                         'unlimited)))
     (extra-special-file
      "/usr/bin/env"
      (file-append coreutils "/bin/env"))
     (service thermald-service-type)
     (service docker-service-type)
     (service libvirt-service-type
              (libvirt-configuration
               (unix-sock-group "libvirt")
               (tls-port "16555")))
     (service cups-service-type
              (cups-configuration
               (web-interface? #t)
               (extensions (list cups-filters))))
     (service nix-service-type)
     (bluetooth-service #:auto-enable? #t)
     (service slim-service-type
              (slim-configuration
               (gnupg? #t)
               (auto-login? #t)
               (default-user "comrade-martin")
               (xorg-configuration
                (xorg-configuration
                 (keyboard-layout keyboard-layout)
                 (extra-config
                  (list %xorg-libinput-config))))))
     (service openssh-service-type
              (openssh-configuration
               (password-authentication? #t)
             ; (authorized-keys
             ;  `(("anton" ,(local-file "anton.pub"))))
               ))
     (modify-services
      %desktop-services
      (delete gdm-service-type)
      (elogind-service-type
       config => (elogind-configuration
                  (inherit config)
                  (handle-lid-switch-external-power 'suspend)))
      (udev-service-type
       config => (udev-configuration
                  (inherit config)
                  (rules
                   (cons*
                    %backlight-udev-rule
                    %trackpoint-udev-rule
                    (udev-configuration-rules config))))))))

   ;; Allow resolution of '.local' host names with mDNS.
   (name-service-switch %mdns-host-lookup-nss)

   ;; Let wheel members root access without inputing root password.
   (sudoers-file (plain-file "sudoers" "root ALL=(ALL) ALL\n%wheel ALL=(ALL) NOPASSWD:ALL\n"))))

#+END_SRC

** Machines
*** Per-System Settings

Some settings need to be customized on a per-system basis without
twaking individual configuration files. With =org-mode='s
~noweb~ functionality, we can define a set of variables that can be
tweaked for each system and applied across configuration files when
they are generated.

Retrieval of these variables is done with ~custom/system-setting-get~.

#+BEGIN_SRC emacs-lisp :noweb yes :tangle ../../build/.config/emacs/per-system-settings.el

  (require 'map) ;; for map-merge

  (setq custom/system-settings
        (map-merge
         'list
         '((desktop/dpi . 180)
           (desktop/background . "KOCMOC.png")

           (emacs/default-face-size  . 220)
           (emacs/variable-face-size . 245)
           (emacs/fixed-face-size    . 200)

           (polybar/height      . 25)
           (polybar/font-0-size . 18)
           (polybar/font-1-size . 14)
           (polybar/font-2-size . 20)
           (polybar/font-3-size . 13)

           (dunst/font-size     . 20)
           (dunst/max-icon-size . 80)

           (vimb/default-zoom        . 100)
           (qutebrowser/default-zoom . 100))
         <<system-settings>>))

#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle ../../build/.config/emacs/lisp/custom-system-settings.el

  (defun custom/system-settings-load ()
    (interactive)
    (load-file "~/dotfiles/build/.config/emacs/per-system-settings.el"))

  (defun custom/system-settings-get (setting)
    (alist-get setting custom/system-settings))

  (provide 'custom-system-settings)

#+END_SRC

*** КИРПИЧ (BRICK)

- =ThinkPad X220=
- permanent [[https://youtu.be/dz6XmUFoG2k][heavy-duty]] shell (=Mobilis OPTIMUM= - discontinued)
- ISO keyboard
- 300GB HDD

#+BEGIN_SRC conf-space :tangle ../../build/.ssh/config

  Host kirpich-local
  	HostName kirpich
  	User comrade-martin

#+END_SRC

~~/.config/guix/systems/kirpich.scm~:

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/systems/kirpich.scm

  (define-module (kirpich)
    #:use-module (base-system)
    #:use-module (gnu)
    #:use-module (nongnu packages linux))

  (operating-system
   (inherit base-operating-system)
   (host-name "kirpich")

   (firmware (list linux-firmware))

   (swap-devices
    (list (uuid "67928664-36ed-4dd2-8454-ec0a9a2a7c53")))

   (mapped-devices
    (list (mapped-device
           (source (uuid "dacfe575-0d48-492e-8907-8e3db38d0f1e"))
           (target "ROOT")
           (type luks-device-mapping))))

   (file-systems
    (cons* (file-system
            (mount-point "/")
            (device "/dev/mapper/ROOT")
            (type "btrfs")
            (dependencies mapped-devices))
           (file-system
            (mount-point "/boot/efi")
            (device (uuid "D6A9-57EB" 'fat32))
            (type "vfat"))
           %base-file-systems)))

#+END_SRC

*System Settings*

#+BEGIN_SRC emacs-lisp :noweb-ref system-settings :noweb-sep ""

  (when (equal system-name "kirpich")
    '((desktop/dpi . 125)

      (emacs/default-face-size  . 190)
      (emacs/variable-face-size . 200)
      (emacs/fixed-face-size    . 190)

      (polybar/height      . 15)
      (polybar/font-0-size . 16)
      (polybar/font-1-size . 12)
      (polybar/font-2-size . 18)
      (polybar/font-3-size . 11)

      (dunst/font-size     . 20)
      (dunst/max-icon-size . 80)

      (vimb/default-zoom        . 100)
      (qutebrowser/default-zoom . 100)))

#+END_SRC

*** Anton

#+BEGIN_SRC conf-space :tangle ../../build/.ssh/config

  Host anton-local
        HostName anton
        User martinmake
        Port 22

  Host anton-remote
        HostName noname
        User martinmake
        ProxyCommand openssl s_client -quiet -connect anton.michalec.dev -servername server1
        Port 22

#+END_SRC

** USB Installation Image

To install =GNU GuixSD= on another machine, you first need to build a
USB image. In order to use "any" WIFI card during installation, we
have to use non-free ~linux-firmware~.

~~/.config/guix/systems/install.scm~:

#+BEGIN_SRC scheme :tangle ../../build/.config/guix/systems/install.scm

  (define-module (install)
    #:use-module (gnu system)
    #:use-module (gnu system install)
    #:use-module (gnu packages package-management)
    #:use-module (gnu packages version-control)
    #:use-module (gnu packages file-systems)
    #:use-module (gnu packages linux)
    #:use-module (gnu packages mtools)
    #:use-module (gnu packages vim)
    #:use-module (gnu packages curl)
    #:use-module (gnu packages emacs)
    #:use-module (nongnu packages linux)
    #:export (installation-os-nonfree))

  (define installation-os-nonfree
    (operating-system
      (inherit installation-os)
      (kernel linux)
      (firmware (list linux-firmware))

      ;; Add the 'net.ifnames' argument to prevent network interfaces
      ;; from having really long names.  This can cause an issue with
      ;; wpa_supplicant when you try to connect to a wifi network.
      (kernel-arguments '("quiet" "modprobe.blacklist=radeon" "net.ifnames=0"))

      ;; Add some extra packages useful for the installation process
      (packages
       (append (list
                exfat-utils
                fuse-exfat
                git
                curl
                stow
                vim
                emacs-no-x-toolkit)
               (operating-system-packages installation-os)))))

  installation-os-nonfree

#+END_SRC

* System Configuration
** Profile
*** Guix

#+BEGIN_SRC shell :tangle ../../build/.profile :tangle-mode (identity #o444)

  # Load the default Guix profile
  GUIX_PROFILE="$HOME/.guix-profile"
  source "$GUIX_PROFILE"/etc/profile

  # Load extra Guix profiles
  GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
  for profile in $GUIX_EXTRA_PROFILES/*; do
      profile=$profile/$(basename "$profile")
          if [ -f $profile/etc/profile ]; then
              GUIX_PROFILE=$profile
              source $GUIX_PROFILE/etc/profile
          fi
          unset profile
  done

#+END_SRC

*** Nix

#+BEGIN_SRC shell :tangle ../../build/.profile :tangle-mode (identity #o444)

  # Load Nix environment
  if [ -f /run/current-system/profile/etc/profile.d/nix.sh ]; then
      source /run/current-system/profile/etc/profile.d/nix.sh
  fi

#+END_SRC

*** Enviromental Variables

#+BEGIN_SRC shell :tangle ../../build/.profile :tangle-mode (identity #o444)

  unset PULSE_CONFIG
  unset PULSE_CLIENTCONFIG

  export VISUAL="emacsclient -a vim"
  export EDITOR="$VISUAL"
  export BROWSER="vimb"

  export XDG_CONFIG_HOME="$HOME/.config/"
  export XDG_DATA_HOME="$HOME/.local/share/"
  # Make Flatpak apps visible to launcher
  export XDG_DATA_DIRS="$XDG_DATA_DIRS:$HOME/.local/share/flatpak/exports/share"
  # Make applications in other profiles visible to launcher
  export XDG_DATA_DIRS="$XDG_DATA_DIRS:$HOME/.guix-extra-profiles/*/*/share"

  export PATH="$PATH:$HOME/.local/bin/"
  export PATH="$PATH:$HOME/dotfiles/script/"
  export PATH="$PATH:$HOME/.cargo/bin/"
  export PATH="$PATH:$HOME/.npm-global/bin/"

  export EMACS_USER_DIRECTORY="$XDG_DATA_HOME/emacs/"

  # Export the path to IcedTea so that tools pick it up correctly
  export JAVA_HOME=$(dirname $(dirname $(readlink $(which java))))

  # Make sure we can reach the GPG agent for SSH auth
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

  # Make sure `ls` collates dotfiles first (for dired)
  export LC_COLLATE="C"

  # Many build scripts expect CC to contain the compiler command
  export CC="gcc"

#+END_SRC

*** Font fix

#+BEGIN_SRC shell :tangle ../../build/.profile :tangle-mode (identity #o444)

  # Ensure that font folders are loaded correctly
  xset +fp $(dirname $(readlink -f ~/.guix-extra-profiles/desktop/desktop/share/fonts/truetype/fonts.dir))

#+END_SRC

*** Keyboard

#+BEGIN_SRC shell :tangle ../../build/.profile :tangle-mode (identity #o444)

  # Switch escape and caps if tty:
  sudo -n loadkeys "$XDG_CONFIG_HOME/kmap/colemak_custom_iso.kmap"
  set -o noclobber

#+END_SRC

*** Color Palette

#+BEGIN_SRC shell :tangle ../../build/.profile :tangle-mode (identity #o444)

  print "\e]P0000000" #black
  print "\e]P1cd0000" #darkred
  print "\e]P200cd00" #darkgreen
  print "\e]P3cdcd00" #brown
  print "\e]P40000cd" #darkblue
  print "\e]P5cd00cd" #darkmagenta
  print "\e]P600cdcd" #darkcyan
  print "\e]P7e5e5e5" #lightgrey
  print "\e]P84d4d4d" #darkgrey
  print "\e]P9ff0000" #red
  print "\e]PA00ff00" #green
  print "\e]PBffff00" #yellow
  print "\e]PC0000ff" #blue
  print "\e]PDff00ff" #magenta
  print "\e]PE00ffff" #cyan
  print "\e]PFffffff" #white
  clear # remove background artifacting if any
  # white block cursor
  print "\e[?16;2;112;c"
  setterm -background black -foreground white -store

#+END_SRC

*** Start

#+BEGIN_SRC shell :tangle ../../build/.profile :tangle-mode (identity #o444)

  clear
  neofetch

#+END_SRC

** ZSH

#+BEGIN_SRC shell :tangle ../../build/.zprofile :tangle-mode (identity #o444)

  # Honor system-wide environment variables
  source /etc/profile

#+END_SRC

** BASH

#+BEGIN_SRC shell :tangle ../../build/.bash_profile :tangle-mode (identity #o444)

  # Load .profile
  if [ -f ~/.profile ]; then source ~/.profile; fi

  # Honor per-interactive-shell startup file
  if [ -f ~/.bashrc ]; then source ~/.bashrc; fi

#+END_SRC

#+BEGIN_SRC shell :tangle ../../build/.bashrc :tangle-mode (identity #o444)

  # Bash initialization for interactive non-login shells and
  # for remote shells (info "(bash) Bash Startup Files").

  # Export 'SHELL' to child processes.  Programs such as 'screen'
  # honor it and otherwise use /bin/sh.
  export SHELL

  if [[ $- != *i* ]]
  then
      # We are being invoked from a non-interactive shell.  If this
      # is an SSH session (as in "ssh host command"), source
      # /etc/profile so we get PATH and other essential variables.
      [[ -n "$SSH_CLIENT" ]] && source /etc/profile

      # Don't do anything else.
      return
  fi

  # Source the system-wide file.
  source /etc/bashrc

  # Adjust the prompt depending on whether we're in 'guix environment'.
  if [ -n "$GUIX_ENVIRONMENT" ]
  then
      PS1='\u@\h \w [env]\$ '
  else
      PS1='\u@\h \w\$ '
  fi
  alias ls='ls -p --color=auto'
  alias ll='ls -l'
  alias grep='grep --color=auto'

#+END_SRC

** Shepard

#+BEGIN_SRC scheme :tangle ../../build/.config/shepard/init.scm

  (define gpg-agent
    (make <service>
      #:provides '(gpg-agent)
      #:respawn? #t
      #:start (make-system-constructor "gpg-connect-agent /bye")
      #:stop (make-system-destructor "gpgconf --kill gpg-agent")))

  (define mcron
    (make <service>
      #:provides '(mcron)
      #:respawn? #t
      #:start (make-forkexec-constructor '("mcron"))
      #:stop  (make-kill-destructor)))

  (define syncthing
    (make <service>
      #:provides '(syncthing)
      #:respawn? #t
      #:start (make-forkexec-constructor '("syncthing" "-no-browser"))
      #:stop  (make-kill-destructor)))

  (define pulseaudio
    (make <service>
      #:provides '(pulseaudio)
      #:respawn? #t
      #:start (make-forkexec-constructor '("pulseaudio"))
      #:stop  (make-kill-destructor)))

  (register-services gpg-agent mcron syncthing pulseaudio)

  (action 'shepherd 'daemonize)

  ;; Start user services
  (for-each start '(mcron))

#+END_SRC

** Udiskie

*Guix Packages*

#+BEGIN_SRC scheme :noweb-ref packages :noweb-sep ""

  "udiskie"

#+END_SRC

* Scheduled Tasks

I use [[https://www.gnu.org/software/mcron/][GNU mcron]] for scheduling tasks to run periodically in the background.

*Guix Packages*

#+BEGIN_SRC scheme :noweb-ref packages :noweb-sep ""

  "mcron"

#+END_SRC

* System Tools

*Guix Packages*

#+BEGIN_SRC scheme :noweb-ref packages :noweb-sep ""

  "openssh"
  "zip"
  "unzip"

#+END_SRC

* System Management

#+BEGIN_SRC shell :tangle ../../script/system-reconfigure

  cd $HOME/dotfiles
  source../../script/utilities.sh

  echo -e "${NEUTRAL} Reconfiguring $(hostname)..."
  sudo -E guix system -L $XDG_CONFIG_HOME/guix/systems \
       reconfigure $XDG_CONFIG_HOME/guix/systems/$(hostname).scm \
       && echo -e "${GOOD} Reconfigured $(hostname)." \
       || echo -e "${BAD} Unable to reconfigure $(hostname)!"

#+END_SRC

#+BEGIN_SRC makefile

.PHONY: system-reconfigure
system-reconfigure: ## Create new iteration of GuixSD system configuration.
	@system-reconfigure

  #+END_SRC

#+END_SRC

* Nix Package Management

Certains tools are not easily available through =Guix= channels, but we
can use the =Nix= package repository.

#+BEGIN_SRC conf :tangle ../../build/.nix-channels

  https://nixos.org/channels/nixpkgs-unstable nixpkgs

#+END_SRC

The channel needs to be updated before any package can be installed:

#+BEGIN_SRC shell :tangle no

  nix-channel --update

#+END_SRC

Installing packages:

#+BEGIN_SRC shell :tangle no

  nix-env -i nodejs dotnet-sdk gh hledger
# nix-env -iA nixpkgs.nodejs-12_x # For a specific version

#+END_SRC

Allow specific =unfree= packages.

#+BEGIN_SRC conf :tangle no

  { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
      "spotify"
    ];
  }

#+END_SRC

* System Installation
** Building the Installation Image

use the non-free kernel and firmware blobs from the [[https://gitlab.com/nonguix/nonguix][nonguix]] channel.

After cloning the repo, the installation image can be built with this
command:

#+BEGIN_SRC shell

  guix system image../../install.scm --image-size=5G

#+END_SRC

#+begin_quote

NOTE:* It can take an hour or more for this to complete, so be patient...

#+end_quote

Once the build is complete, Guix will print out the path to the disk
image file that was created. You can now write the installation image
to a USB stick using ~dd~:

#+BEGIN_SRC shell

  sudo dd if=/gnu/store/nyg6jv3a4l0pbcvb0x7jfsb60k9qalga-disk-image of=/dev/sdX status=progress

#+END_SRC

** Installing GNU GuixSD

We boot into our custom installation image and choose: =Install using the shell based program=.

*** Setting Up WiFi

Create a file with WiFi configuration:

~wifi.conf~

#+BEGIN_SRC conf

  network = {
    ssid = "ssid-name"
    key_mgmt = WPA-PSK
    psk = "passphrase"
  }

#+END_SRC

Run the following commands to unblock the WiFi card, determine its
device name, and connect using the device name you received from
~ifconfig -a~.

#+BEGIN_SRC shell

  rfkill unblock all
  ifconfig -a
  wpa_supplicant -c../../wifi.conf -i wlan0 -B

#+END_SRC

Run ~dhclient~ to turn on DNS for our WiFi interface.

#+BEGIN_SRC shell

  dhclient -v wlan0

#+END_SRC

*** Creating Partitions

We'll create the following partition table:

| Device    | Label | Type             | Filesystem   | Size   | Mountpoint |
|-----------+-------+------------------+--------------+--------+------------|
| /dev/sda1 | BOOT  | EFI System       | vfat (32)    | 256M   | /boot/efi  |
| /dev/sda2 | SWAP  | Linux swap       | swsuspend    | RAM*2  | /N/A/        |
| /dev/sda3 | ROOT  | Linux Filesystem | LUKS (btrfs) | <REST> | /          |

#+begin_quote

*NOTE:* We're only concerned with UEFI, at least for now.

#+end_quote

Tools to use:

#+BEGIN_SRC shell

  cfdisk /dev/sda \
      || fdisk /dev/sda

  mkfs.fat -F32 /dev/sda1 \
      && fatlabel /dev/sda1 -L BOOT

  mkswap -L SWAP /dev/sda2

  cryptsetup luksformat /dev/nvme0n1p5
  cryptsetup open --type luks /dev/nvme0n1p5 system-root
  mkfs.btrfs -L ROOT /dev/mapper/ROOT

#+END_SRC

Mounting partitions:

#+BEGIN_SRC shell

  mount label=ROOT /mnt

  mkdir /mnt/boot/efi
  mount label=BOOT /mnt/boot/efi

  swapon -L SWAP

#+END_SRC

Since everything installed with ~guix~ is placed into ~/gnu/store/~, we
can make it =Copy On Write= to our new system.

#+BEGIN_SRC shell

  herd start cow-store /mnt

#+END_SRC

*** Initial System Installation

We pull down our system configuration into the installation FS (not
~/mnt~):

#+BEGIN_SRC shell

  git clone https://github.com/martinmake/dotfiles

#+END_SRC

We pull =guix channels= on installer system making sure we also pull
~nonguix~ channel:

#+BEGIN_SRC shell

  guix pull -C../../dotfiles/build/.config/guix/channels.scm
  hash guix

#+END_SRC

We update/create new operating system with partition UUIDs.

#+BEGIN_SRC shell

  ls -l /dev/disk/by-uuid/../../dotfiles/build/.config/guix/systems/<SYSTEM>.scm
  vim../../dotfiles/build/.config/guix/systems/<SYSTEM>.scm

#+END_SRC

We also push this chage to remote:

#+BEGIN_SRC shell

  git commit -am "added machine: <machine_name>"
  git push

#+END_SRC

We initialize our system (this will take a while):

#+BEGIN_SRC shell

  guix system -L../../dotfiles/build/.config/guix/systems/ \
       init../../dotfiles/build/.config/guix/systems/<SYSTEM>.scm /mnt

#+END_SRC

*** Initial System Setup

We reboot into the new GNU GuixSD, to finish initial setup.

First we want to set root and user password:

#+BEGIN_SRC shell

  passwd
  passwd <username>

#+END_SRC

Now we log into our user account and clone dotfiles repository.

#+BEGIN_SRC shell

  git clone https://github.com/martinmake/dotfiles

#+END_SRC

Setup channels... (make sure to pull)

Activate profiles:

#+BEGIN_SRC shell

  profiles-activate desktop emacs

#+END_SRC

Now we have packages from those manifests installed and usable. They
be later updated with ~profiles-update~.
