#!/usr/bin/env sh

OPTIONS=""
COMMAND=""
PURE=false

while getopts :epd: opt; do
	case $opt in
		e) break ;;
		p) PURE=true ;;
		?) OPTIONS+="-$OPTARG " ;;
	esac
done

PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)
PID=$(($(echo "$(pstree -lpA "$PID" | tail -n 1)" | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g') + 1))
DIRECTORY="$(readlink /proc/"$PID"/cwd)"
[ ! -d "${DIRECTORY}" ] && DIRECTORY=$HOME

shift $(($OPTIND -1))
COMMAND="$@"

[ ${PURE} = true ] && USE_TMUX=false || USE_TMUX=true
DIRECTORY=${DIRECTORY} USE_TMUX=${USE_TMUX} SHELL_COMMAND=${COMMAND} exec st ${OPTIONS}
