#!/bin/bash

MIDDLE_FILE=$(mktemp /tmp/better-bear.XXXXXXXXXXX)
TMP_FILE=$(mktemp /tmp/better-bear.XXXXXXXXXXX)
COMPILE_COMMANDS_FILE=compile_commands.json

SDIR=$1
IDIRS=$(echo $@ | cut -d' ' -f2- | sed 's|/|\\/|g')

make clean NO_DEPENDENCIES=TRUE
bear make --keep-going

head -n -1 $COMPILE_COMMANDS_FILE > $TMP_FILE; mv $TMP_FILE $COMPILE_COMMANDS_FILE
cat $COMPILE_COMMANDS_FILE | tail -n+2 > $MIDDLE_FILE
for IDIR in $IDIRS; do
	echo ","                                 >> $COMPILE_COMMANDS_FILE
	cat $MIDDLE_FILE | sed "/        \"file\": \"/s/$SDIR/$IDIR/g" >> $COMPILE_COMMANDS_FILE
done
echo ']' >> $COMPILE_COMMANDS_FILE
